<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

/**
 * source code generated by http://restunited.com using Swagger Codegen
 * for any feedback/issue, please send to feedback{at}restunited.com
 *
 * swagger-codegen: https://github.com/wordnik/swagger-codegen
 */

/**
 * APIClient.php
 */

namespace HackerRank\models;

class Codes {

  static $swaggerTypes = array(
      'bash' => 'int',
      'c' => 'int',
      'clisp' => 'int',
      'clojure' => 'int',
      'cpp' => 'int',
      'csharp' => 'int',
      'erlang' => 'int',
      'go' => 'int',
      'haskell' => 'int',
      'java' => 'int',
      'lua' => 'int',
      'mysql' => 'int',
      'oracle' => 'int',
      'perl' => 'int',
      'php' => 'int',
      'python' => 'int',
      'ruby' => 'int',
      'scala' => 'int'

    );

  /**
  * Bash
  */
  public $bash; // int
  /**
  * C
  */
  public $c; // int
  /**
  * Clisp
  */
  public $clisp; // int
  /**
  * Clojure
  */
  public $clojure; // int
  /**
  * Cpp
  */
  public $cpp; // int
  /**
  * Csharp
  */
  public $csharp; // int
  /**
  * Erlang
  */
  public $erlang; // int
  /**
  * Go
  */
  public $go; // int
  /**
  * Haskell
  */
  public $haskell; // int
  /**
  * Java
  */
  public $java; // int
  /**
  * Lua
  */
  public $lua; // int
  /**
  * Mysql
  */
  public $mysql; // int
  /**
  * Oracle
  */
  public $oracle; // int
  /**
  * Perl
  */
  public $perl; // int
  /**
  * Php
  */
  public $php; // int
  /**
  * Python
  */
  public $python; // int
  /**
  * Ruby
  */
  public $ruby; // int
  /**
  * Scala
  */
  public $scala; // int
  }

